# Open graphics
/vis/open OGL

# Draw and verbosity
/vis/drawVolume worlds
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Settings
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/geometry/set/visibility World 0 false
/vis/scene/add/trajectories smooth
/vis/viewer/set/viewpointThetaPhi -30 -20
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories
/vis/scene/add/axes